sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 124.70.14.222
    port: 3306
    database: sky_take_out
    username: root
    password: lk078622
  alioss:
    access-key-id: LTAI5tEVK3CaTsQXzRxZxnh1
    access-key-secret: nBRfAActaWI7FvzHl0rVan9Gu6KSbp
    bucket-name: sky-take-out-dlk
    endpoint: oss-cn-beijing.aliyuncs.com
